server {
    listen 80;

    # 1. React의 정적 파일들을 서빙합니다.
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # React Router 새로고침 에러 방지
    }

    # 2. 클라이언트가 /api 로 요청을 보내면, 백엔드 컨테이너(8080 포트)로 토스합니다.
    location /api {
        proxy_pass http://backend:8080;
    }
}